@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant GameService as gs
participant BetRepositoryInterface
box "Pocket services" #LightGreen
    participant BonusPocketService
    participant CryptoPocketService
    participant FiatPocketService
end box

gs -> BetRepositoryInterface: Create bet entity
gs -> BonusPocketService: is supported pocket
gs -> CryptoPocketService: is supported pocket
gs -> FiatPocketService: is supported pocket
gs -> gs: Choose pocket service
gs -> BonusPocketService: Run bet method.

@enduml