@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant GameService as gs
participant BetRepositoryInterface
box "Pocket services" #LightGreen
    participant BonusPocketService
    participant CryptoPocketService
    participant FiatPocketService
end box

gs -> BonusPocketService: cancel bonus

@enduml