@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant GameService as gs
participant BetRepositoryInterface
box "Pocket services" #LightGreen
    participant BonusPocketService
    participant CryptoPocketService
    participant FiatPocketService
end box

box "Repository" #LightYellow
    participant PocketTransactionRepository
    participant PocketRepositoryInterface
    participant BetTransactionRepositoryInterface
end box

gs -> BonusPocketService: is supported pocket
gs -> CryptoPocketService: is supported pocket
gs -> FiatPocketService: is supported pocket
gs -> gs: Choose pocket service
gs -> BonusPocketService: Run bet refund.
BonusPocketService -> BetTransactionRepositoryInterface: Find pocket transaction by bet id
BonusPocketService -> PocketTransactionRepository: Find bet pocket money for transaction
BonusPocketService -> PocketTransactionRepository: Create new transaction for refund
BonusPocketService -> PocketRepositoryInterface: Add entity with opposite money to each pocket

@enduml